# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plots_layout = QtWidgets.QVBoxLayout()
        self.plots_layout.setObjectName("plots_layout")
        self.gridLayout.addLayout(self.plots_layout, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.temperature_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.temperature_check_box.setObjectName("temperature_check_box")
        self.gridLayout_2.addWidget(self.temperature_check_box, 3, 0, 1, 1)
        self.wind_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.wind_check_box.setObjectName("wind_check_box")
        self.gridLayout_2.addWidget(self.wind_check_box, 1, 0, 1, 1)
        self.pressure_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.pressure_check_box.setObjectName("pressure_check_box")
        self.gridLayout_2.addWidget(self.pressure_check_box, 0, 0, 1, 1)
        self.precipitation_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.precipitation_check_box.setObjectName("precipitation_check_box")
        self.gridLayout_2.addWidget(self.precipitation_check_box, 2, 0, 1, 1)
        self.clouds_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.clouds_check_box.setObjectName("clouds_check_box")
        self.gridLayout_2.addWidget(self.clouds_check_box, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.map_layout = QtWidgets.QVBoxLayout()
        self.map_layout.setObjectName("map_layout")
        self.widget3d = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget3d.sizePolicy().hasHeightForWidth())
        self.widget3d.setSizePolicy(sizePolicy)
        self.widget3d.setMinimumSize(QtCore.QSize(386, 484))
        self.widget3d.setObjectName("widget3d")
        self.map_layout.addWidget(self.widget3d)
        self.gridLayout.addLayout(self.map_layout, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.city_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.city_combo_box.setObjectName("city_combo_box")
        self.verticalLayout.addWidget(self.city_combo_box)
        self.date_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.date_combo_box.setObjectName("date_combo_box")
        self.verticalLayout.addWidget(self.date_combo_box)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lat_lon_label = QtWidgets.QLabel(self.centralwidget)
        self.lat_lon_label.setText("")
        self.lat_lon_label.setObjectName("lat_lon_label")
        self.verticalLayout.addWidget(self.lat_lon_label)
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setText("")
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.temperature_label = QtWidgets.QLabel(self.centralwidget)
        self.temperature_label.setText("")
        self.temperature_label.setObjectName("temperature_label")
        self.verticalLayout.addWidget(self.temperature_label)
        self.pressure_label = QtWidgets.QLabel(self.centralwidget)
        self.pressure_label.setText("")
        self.pressure_label.setObjectName("pressure_label")
        self.verticalLayout.addWidget(self.pressure_label)
        self.precipitation_label = QtWidgets.QLabel(self.centralwidget)
        self.precipitation_label.setText("")
        self.precipitation_label.setObjectName("precipitation_label")
        self.verticalLayout.addWidget(self.precipitation_label)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.temperature_check_box.setText(_translate("MainWindow", "Temperature"))
        self.wind_check_box.setText(_translate("MainWindow", "Wind"))
        self.pressure_check_box.setText(_translate("MainWindow", "Pressure"))
        self.precipitation_check_box.setText(_translate("MainWindow", "Precipitation"))
        self.clouds_check_box.setText(_translate("MainWindow", "Clouds"))
        self.start_button.setText(_translate("MainWindow", "SHOW"))

